package com.example.ui

object Localization {
    fun get(key: String, lang: String, vararg args: Any): String {
        val map = when (lang) {
            "en" -> englishMap
            "ko" -> koreanMap
            "zh" -> chineseMap
            else -> japaneseMap
        }
        val template = map[key] ?: japaneseMap[key] ?: key
        return try {
            String.format(template, *args)
        } catch (e: Exception) {
            template
        }
    }

    private val japaneseMap = mapOf(
        "all" to "すべて",
        "unanalyzed" to "未解析",
        "waiting_ai" to "未解析 (AI分類待ち)",
        "analyzing" to "%s (%d/%d) を解析中...",
        "analyzing_retry" to "%s (%d/%d) を解析中 (再試行 %d/%d)...",
        "temp_error" to "一時エラー。%d秒後に %s を再試行します...",
        "waiting_next" to "待機中... 次の解析まであと %d秒",
        "canceling" to "解析を中断しています...",
        "batch_complete" to "一括自動解析完了: %d個のアプリが更新されました",
        "batch_cancelled" to "一括自動解析を中断しました (解析完了: %d個)",
        "cancel_toast" to "解析完了: %d個",
        "cancel_btn" to "中止する",
        "custom_bg_success" to "背景画像を設定しました",
        "custom_bg_fail" to "画像の保存に失敗しました: %s",
        "search_placeholder" to "アプリ、カテゴリ、タグを検索...",
        "no_apps" to "アプリが見つかりません",
        "running_analysis" to "AI解析を実行中...",
        "settings_title" to "設定",
        "lang_title" to "AI解析・生成・UI言語設定",
        "lang_desc" to "AIが生成するカテゴリ名、説明文、タグ、関連リンク、およびアプリUI全体の表示言語を指定できます。今後新しくアプリを解析する際にもこの言語が適用されます。",
        "album_select" to "アルバムから画像を選択する...",
        "bg_preset_title" to "宇宙空間の背景壁紙",
        "bg_preset_desc" to "AIアプリランチャーを彩る美しいSF的な宇宙背景画像を設定できます。",
        "bg_custom_url" to "カスタム画像URLを入力...",
        "ok" to "OK",
        "cancel" to "キャンセル",
        "set" to "設定する",
        "custom_url_prompt" to "またはカスタム画像のURLを入力してください:",
        "ai_model_title" to "AIモデル詳細設定",
        "ai_model_desc" to "アプリの特徴解析やカテゴリ分類に使用するGemini APIのモデルを選択できます。デフォルトのままで問題なく機能します。",
        "primary_model" to "メイン解析モデル",
        "backup_model" to "バックアップ解析モデル",
        "embedding_model" to "埋め込みモデル",
        "data_manage_title" to "キャッシュとデータ管理",
        "data_manage_desc" to "ランチャー全体のカテゴリ、説明文、お気に入りなどのAI解析データをすべてリセットし、再解析できるようにします。インストール済みアプリは削除されません。",
        "reset_btn" to "解析データを完全にリセットする",
        "reset_success" to "解析データをリセットしました",
        "reset_confirm_title" to "リセットしますか？",
        "reset_confirm_desc" to "この操作は取り消せません。すべてのAI解析データが削除されます。",
        "app_info_title" to "アプリ情報",
        "tags_label" to "タグ",
        "related_links_label" to "関連リンク・外部情報",
        "open_app" to "アプリを起動する",
        "analyze_btn" to "AIで詳細解析する",
        "no_ai_details" to "このアプリのAI解析データはありません。「AIで詳細解析する」ボタンを押して解析してください。",
        "quick_tag" to "クイックお気に入り",
        "is_favorite" to "お気に入りに追加",
        "not_favorite" to "お気に入りから削除",
        "unknown_category" to "その他 / 未分類",
        "no_links" to "関連リンクはありません",
        "search_all_header" to "すべて表示",
        "no_unamalyzed_apps" to "未解析のアプリはありません",
        "auto_analyze_all" to "未解析アプリを一括解析する",
        "launch_error" to "アプリを起動できませんでした (%s)",
        "init_error" to "起動エラー: %s",
        "analysis_success" to "%s の解析に成功しました",
        "analysis_failed" to "%s の解析に失敗しました。設定でAPIキーを確認してください。",
        "general_error" to "エラー: %s",
        "all_analyzed" to "すべてのアプリは既に解析済みです",
        "clear_cache_success" to "キャッシュをすべてクリアしました",
        "security_warning_title" to "【セキュリティ警告】",
        "security_warning_desc" to "本アプリはプロトタイプ動作のためにAPIキーを参照しています。Android APKファイルは簡単にデコンパイル可能であり、BuildConfig等からキーが抽出される恐れがあります。第三者とAPKを共有する際は、必ず自身の本番用APIキーを差し引くか、バックエンドプロキシを利用する本番用構成をご検討ください。",
        "dialog_custom_bg_title" to "カスタム背景画像URL",
        "dialog_custom_bg_desc" to "表示させたいNASAの星雲などの画像URL(JPG/PNG)を入力してください。",
        "back_btn" to "戻る",
        "primary_model_label" to "デフォルト テキストモデル",
        "backup_model_label" to "サブ テキストモデル (フォールバック)",
        "embedding_model_label" to "エンベディングモデル",
        "unanalyzed_ribbon_title" to "未解析のアプリがあります",
        "unanalyzed_ribbon_desc" to "AI分類・要約・関連リンクを自動生成します",
        "running_analysis" to "AI解析を実行中...",
        "cancel_btn" to "中止する",
        "no_apps" to "インストール済みアプリがありません",
        "items_count" to "%d個のアプリ",
        "search_placeholder" to "アプリ名やAI解析内容を検索...",
        "search_icon_desc" to "検索",
        "clear_btn_desc" to "クリア",
        "ai_summary_title" to "AIによる要約",
        "related_suggestions" to "類似したおすすめアプリ",
        "re_analyze" to "再解析する",
        "close_btn" to "閉じる",
        "link_error" to "リンクを開けませんでした: %s",
        "no_ai_details_title" to "このアプリは未解析です",
        "no_ai_details_desc" to "AI解析を実行すると、自動でカテゴリ分類、要約、ハッシュタグ、関連リンクが生成されます。",
        "gemini_api_key_label" to "Gemini API キー (カスタム)",
        "gemini_api_key_placeholder" to "APIキーを入力 (空欄の場合はデフォルトキーを使用)",
        "correction_context_title" to "AI解析の補正用追加情報 (任意)",
        "correction_text_placeholder" to "AIへの指示や補正用テキストを入力...",
        "choose_file_btn" to "ファイル添付",
        "selected_file_label" to "選択ファイル: %s",
        "vector_utility" to "実用・効率",
        "vector_productivity" to "生産性・業務",
        "vector_social" to "交流・通信",
        "vector_entertainment" to "エンタメ・娯楽",
        "vector_creativity" to "創造・表現",
        "vector_knowledge" to "知性・情報",
        "vector_title" to "AI多次元ベクトル特性解析"
    )

    private val englishMap = mapOf(
        "all" to "All",
        "unanalyzed" to "Unanalyzed",
        "waiting_ai" to "Unanalyzed (Waiting for AI)",
        "analyzing" to "Analyzing %s (%d/%d)...",
        "analyzing_retry" to "Analyzing %s (%d/%d) (Retry %d/%d)...",
        "temp_error" to "Temporary error. Retrying %s in %d seconds...",
        "waiting_next" to "Waiting... Next analysis in %d seconds",
        "canceling" to "Canceling analysis...",
        "batch_complete" to "Batch analysis completed: %d apps updated",
        "batch_cancelled" to "Batch analysis cancelled (%d apps analyzed)",
        "cancel_toast" to "Analyzed: %d apps",
        "cancel_btn" to "Cancel",
        "custom_bg_success" to "Background image updated successfully",
        "custom_bg_fail" to "Failed to save image: %s",
        "search_placeholder" to "Search apps, categories, tags...",
        "no_apps" to "No apps found",
        "running_analysis" to "Running AI analysis...",
        "settings_title" to "Settings",
        "lang_title" to "AI & UI Language Configuration",
        "lang_desc" to "Configure the language used for AI-generated categories, descriptions, tags, related links, and the launcher UI. Future app analysis will also use this language.",
        "album_select" to "Select image from album...",
        "bg_preset_title" to "Space Background Wallpaper",
        "bg_preset_desc" to "Choose beautiful sci-fi cosmic background scenes for your AI App Launcher.",
        "bg_custom_url" to "Enter custom image URL...",
        "ok" to "OK",
        "cancel" to "Cancel",
        "set" to "Set Wallpaper",
        "custom_url_prompt" to "Or enter custom image URL:",
        "ai_model_title" to "AI Model Configuration",
        "ai_model_desc" to "Select the Gemini API models used for app analysis and categorization. Default models work perfectly.",
        "primary_model" to "Primary Analysis Model",
        "backup_model" to "Backup Analysis Model",
        "embedding_model" to "Embedding Model",
        "data_manage_title" to "Cache & Data Management",
        "data_manage_desc" to "Reset all AI-analyzed data (categories, summaries, favorites, etc.) to re-analyze apps. Installed apps will not be uninstalled.",
        "reset_btn" to "Reset All Analysis Data",
        "reset_success" to "Analysis data has been reset",
        "reset_confirm_title" to "Reset analysis data?",
        "reset_confirm_desc" to "This action cannot be undone. All AI analysis results will be deleted.",
        "app_info_title" to "App Information",
        "tags_label" to "Tags",
        "related_links_label" to "Related Links & Resources",
        "open_app" to "Launch App",
        "analyze_btn" to "Analyze with AI",
        "no_ai_details" to "No AI analysis data available. Click 'Analyze with AI' to get started.",
        "quick_tag" to "Quick Favorites",
        "is_favorite" to "Add to Favorites",
        "not_favorite" to "Remove from Favorites",
        "unknown_category" to "Other / Uncategorized",
        "no_links" to "No related links found",
        "search_all_header" to "Search All",
        "no_unamalyzed_apps" to "No unanalyzed apps found",
        "auto_analyze_all" to "Analyze All Unanalyzed Apps",
        "launch_error" to "Could not launch app (%s)",
        "init_error" to "Launch error: %s",
        "analysis_success" to "Successfully analyzed %s",
        "analysis_failed" to "Failed to analyze %s. Please check your API key in Settings.",
        "general_error" to "Error: %s",
        "all_analyzed" to "All apps are already analyzed",
        "clear_cache_success" to "All cache cleared successfully",
        "security_warning_title" to "【Security Notice】",
        "security_warning_desc" to "This app references API keys for prototyping. Android APKs can be decompiled easily, meaning keys can be extracted from BuildConfig. Before sharing the APK with anyone, please remove your production API keys or use a secure backend proxy.",
        "dialog_custom_bg_title" to "Custom Background Image URL",
        "dialog_custom_bg_desc" to "Please enter a valid JPG/PNG image URL of a nebula or space scene.",
        "back_btn" to "Back",
        "primary_model_label" to "Default Text Model",
        "backup_model_label" to "Sub Text Model (Fallback)",
        "embedding_model_label" to "Embedding Model",
        "unanalyzed_ribbon_title" to "You have unanalyzed apps",
        "unanalyzed_ribbon_desc" to "Generate AI categories, summaries, and related links automatically.",
        "running_analysis" to "AI Analysis running...",
        "cancel_btn" to "Cancel",
        "no_apps" to "No installed apps found",
        "items_count" to "%d items",
        "search_placeholder" to "Search apps & AI insights...",
        "search_icon_desc" to "Search",
        "clear_btn_desc" to "Clear",
        "ai_summary_title" to "AI Summary",
        "related_suggestions" to "Related Suggestions",
        "re_analyze" to "Re-analyze",
        "close_btn" to "Close",
        "link_error" to "Could not open link: %s",
        "no_ai_details_title" to "This app is unanalyzed",
        "no_ai_details_desc" to "Analyzing with AI will automatically generate category classification, summary, hashtags, and related links.",
        "gemini_api_key_label" to "Gemini API Key (Custom)",
        "gemini_api_key_placeholder" to "Enter API key (Blank to use default key)",
        "correction_context_title" to "AI Correction / Context (Optional)",
        "correction_text_placeholder" to "Enter instructions or correction text...",
        "choose_file_btn" to "Attach File",
        "selected_file_label" to "Attached file: %s",
        "vector_utility" to "Utility & System",
        "vector_productivity" to "Productivity & Work",
        "vector_social" to "Social & Connect",
        "vector_entertainment" to "Entertainment & Fun",
        "vector_creativity" to "Creativity & Art",
        "vector_knowledge" to "Knowledge & Info",
        "vector_title" to "AI Vector Characteristic Profile"
    )

    private val koreanMap = mapOf(
        "all" to "전체",
        "unanalyzed" to "미분석",
        "waiting_ai" to "미분석 (AI 분류 대기 중)",
        "analyzing" to "%s 분석 중 (%d/%d)...",
        "analyzing_retry" to "%s 분석 중 (%d/%d) (재시도 %d/%d)...",
        "temp_error" to "일시적인 오류 발생. %d초 후 %s 재시도합니다...",
        "waiting_next" to "대기 중... 다음 분석까지 %d초 남음",
        "canceling" to "분석을 중단하는 중...",
        "batch_complete" to "일괄 자동 분석 완료: %d개의 앱이 업데이트되었습니다",
        "batch_cancelled" to "일괄 자동 분석이 중단되었습니다 (분석 완료: %d개)",
        "cancel_toast" to "분석 완료: %d개",
        "cancel_btn" to "중단하기",
        "custom_bg_success" to "배경 이미지가 설정되었습니다",
        "custom_bg_fail" to "이미지 저장에 실패했습니다: %s",
        "search_placeholder" to "앱, 카테고리, 태그 검색...",
        "no_apps" to "앱을 찾을 수 없습니다",
        "running_analysis" to "AI 분석을 실행 중...",
        "settings_title" to "설정",
        "lang_title" to "AI 분석 및 UI 언어 설정",
        "lang_desc" to "AI가 생성하는 카테고리 이름, 설명문, 태그, 관련 링크 및 앱 UI 전체의 표시 언어를 지정할 수 있습니다. 앞으로 새로 분석되는 앱에도 이 언어가 적용됩니다.",
        "album_select" to "앨범에서 이미지 선택...",
        "bg_preset_title" to "우주 배경 화면",
        "bg_preset_desc" to "AI 앱 런처를 장식할 아름다운 SF적인 우주 배경 이미지를 설정할 수 있습니다.",
        "bg_custom_url" to "사용자 정의 이미지 URL 입력...",
        "ok" to "확인",
        "cancel" to "취소",
        "set" to "설정하기",
        "custom_url_prompt" to "또는 사용자 정의 이미지 URL을 입력하세요:",
        "ai_model_title" to "AI 모델 상세 설정",
        "ai_model_desc" to "앱 특징 분석 및 카테고리 분류에 사용할 Gemini API 모델을 선택할 수 있습니다. 기본 설정으로도 완벽하게 작동합니다.",
        "primary_model" to "메인 분석 모델",
        "backup_model" to "백업 분석 모델",
        "embedding_model" to "임베딩 모델",
        "data_manage_title" to "캐시 및 데이터 관리",
        "data_manage_desc" to "런처 전체의 카테고리, 설명문, 즐겨찾기 등 모든 AI 분석 데이터를 초기화하고 다시 분석할 수 있게 합니다. 설치된 앱은 삭제되지 않습니다.",
        "reset_btn" to "분석 데이터 완전히 초기화",
        "reset_success" to "분석 데이터가 초기화되었습니다",
        "reset_confirm_title" to "초기화하시겠습니까?",
        "reset_confirm_desc" to "이 작업은 취소할 수 없습니다. 모든 AI 분석 데이터가 삭제됩니다.",
        "app_info_title" to "앱 정보",
        "tags_label" to "태그",
        "related_links_label" to "관련 링크 및 외부 정보",
        "open_app" to "앱 실행",
        "analyze_btn" to "AI로 상세 분석",
        "no_ai_details" to "앱의 AI 분석 데이터가 없습니다. 'AI로 상세 분석' 버튼을 눌러 분석해 보세요.",
        "quick_tag" to "퀵 즐겨찾기",
        "is_favorite" to "즐겨찾기 추가",
        "not_favorite" to "즐겨찾기 삭제",
        "unknown_category" to "기타 / 미분류",
        "no_links" to "관련 링크가 없습니다",
        "search_all_header" to "전체 검색",
        "no_unamalyzed_apps" to "미분석 앱이 없습니다",
        "auto_analyze_all" to "미분석 앱 일괄 분석하기",
        "launch_error" to "앱을 실행할 수 없습니다 (%s)",
        "init_error" to "실행 오류: %s",
        "analysis_success" to "%s 분석에 성공했습니다",
        "analysis_failed" to "%s 분석에 실패했습니다. 설정에서 API 키를 확인해 주세요.",
        "general_error" to "오류: %s",
        "all_analyzed" to "모든 앱이 이미 분석되었습니다",
        "clear_cache_success" to "캐시를 모두 삭제했습니다",
        "security_warning_title" to "【보안 경고】",
        "security_warning_desc" to "본 앱은 프로토타입 작동을 위해 API 키를 참조합니다. Android APK 파일은 쉽게 디컴파일될 수 있어 BuildConfig 등에서 키가 유출될 위험이 있습니다. 제3자와 APK를 공유할 때는 반드시 자신의 실서비스용 API 키를 제거하거나, 백엔드 프록시를 이용하는 실서비스용 구성을 고려하시기 바랍니다.",
        "dialog_custom_bg_title" to "사용자 정의 배경 이미지 URL",
        "dialog_custom_bg_desc" to "표시하고 싶은 성운 등의 우주 이미지 URL(JPG/PNG)을 입력하세요.",
        "back_btn" to "뒤로",
        "primary_model_label" to "기본 텍스트 모델",
        "backup_model_label" to "보조 텍스트 모델 (폴백)",
        "embedding_model_label" to "임베딩 모델",
        "unanalyzed_ribbon_title" to "미분석 앱이 있습니다",
        "unanalyzed_ribbon_desc" to "AI 카테고리, 요약, 관련 링크를 자동으로 생성합니다.",
        "running_analysis" to "AI 분석 진행 중...",
        "cancel_btn" to "중지하기",
        "no_apps" to "설치된 앱이 없습니다",
        "items_count" to "%d개 앱",
        "search_placeholder" to "앱 이름 또는 AI 분석 내용 검색...",
        "search_icon_desc" to "검색",
        "clear_btn_desc" to "지우기",
        "ai_summary_title" to "AI 요약",
        "related_suggestions" to "유사한 추천 앱",
        "re_analyze" to "다시 분석",
        "close_btn" to "닫기",
        "link_error" to "링크를 열 수 없습니다: %s",
        "no_ai_details_title" to "이 앱은 미분석 상태입니다",
        "no_ai_details_desc" to "AI 분석을 실행하면 카테고리 분류, 요약, 해시태그, 관련 링크가 자동으로 생성됩니다.",
        "gemini_api_key_label" to "Gemini API 키 (사용자 정의)",
        "gemini_api_key_placeholder" to "API 키 입력 (비어 있는 경우 기본 키 사용)",
        "correction_context_title" to "AI 보정 및 컨텍스트 (선택 사항)",
        "correction_text_placeholder" to "AI 지침 또는 보정 텍스트 입력...",
        "choose_file_btn" to "파일 첨부",
        "selected_file_label" to "첨부 파일: %s",
        "vector_utility" to "실용성 및 시스템",
        "vector_productivity" to "생산성 및 비즈니스",
        "vector_social" to "소셜 및 소통",
        "vector_entertainment" to "엔터테인먼트 및 재미",
        "vector_creativity" to "창의성 및 예술",
        "vector_knowledge" to "정보 및 지식",
        "vector_title" to "AI 벡터 다차원 분석"
    )

    private val chineseMap = mapOf(
        "all" to "全部",
        "unanalyzed" to "未分析",
        "waiting_ai" to "未分析 (等待 AI 分类)",
        "analyzing" to "正在分析 %s (%d/%d)...",
        "analyzing_retry" to "正在分析 %s (%d/%d) (重试 %d/%d)...",
        "temp_error" to "临时错误。将在 %d 秒后重试 %s...",
        "waiting_next" to "等待中... 距离下次分析还有 %d 秒",
        "canceling" to "正在中止分析...",
        "batch_complete" to "一键自动分析完成: 已更新 %d 个应用",
        "batch_cancelled" to "一键自动分析已中止 (已分析: %d 个)",
        "cancel_toast" to "已分析: %d 个",
        "cancel_btn" to "中止",
        "custom_bg_success" to "已成功设置背景图片",
        "custom_bg_fail" to "保存图片失败: %s",
        "search_placeholder" to "搜索应用、分类、标签...",
        "no_apps" to "未找到应用",
        "running_analysis" to "正在执行 AI 分析...",
        "settings_title" to "设置",
        "lang_title" to "AI 分析与 UI 语言设置",
        "lang_desc" to "可以指定 AI 生成的分类名称、说明、标签、相关链接以及应用 UI 整体的显示语言。此语言也适用于今后新分析的应用。",
        "album_select" to "从相册选择图片...",
        "bg_preset_title" to "宇宙空间背景壁纸",
        "bg_preset_desc" to "设置精美的科幻宇宙背景图片，让您的 AI 应用启动器更加炫酷。",
        "bg_custom_url" to "输入自定义图片 URL...",
        "ok" to "确定",
        "cancel" to "取消",
        "set" to "设置壁纸",
        "custom_url_prompt" to "或输入自定义图片的 URL 地址:",
        "ai_model_title" to "AI 模型高级设置",
        "ai_model_desc" to "选择用于应用特征分析及分类的 Gemini API 模型。保持默认值即可正常运行。",
        "primary_model" to "主分析模型",
        "backup_model" to "备份分析模型",
        "embedding_model" to "嵌入模型",
        "data_manage_title" to "缓存与数据管理",
        "data_manage_desc" to "重置整个启动器的分类、说明、收藏等所有 AI 分析数据并重新分析。此操作不会卸载已安装的应用。",
        "reset_btn" to "完全重置所有分析数据",
        "reset_success" to "分析数据已重置",
        "reset_confirm_title" to "确认重置？",
        "reset_confirm_desc" to "此操作无法撤销。所有 AI 分析数据都将被删除。",
        "app_info_title" to "应用信息",
        "tags_label" to "标签",
        "related_links_label" to "相关链接及外部资源",
        "open_app" to "启动应用",
        "analyze_btn" to "AI 详细分析",
        "no_ai_details" to "没有此应用的 AI 分析数据。请点击“AI 详细分析”按钮进行分析。",
        "quick_tag" to "快捷收藏",
        "is_favorite" to "添加至收藏",
        "not_favorite" to "从收藏中移除",
        "unknown_category" to "其他 / 未分类",
        "no_links" to "暂无相关链接",
        "search_all_header" to "搜索全部",
        "no_unamalyzed_apps" to "没有未分析的应用",
        "auto_analyze_all" to "一键分析未分析应用",
        "launch_error" to "无法启动应用 (%s)",
        "init_error" to "启动错误: %s",
        "analysis_success" to "%s 分析成功",
        "analysis_failed" to "%s 分析失败。请在设置中检查 API 密钥。",
        "general_error" to "错误: %s",
        "all_analyzed" to "所有应用都已分析完毕",
        "clear_cache_success" to "已清除所有缓存",
        "security_warning_title" to "【安全警告】",
        "security_warning_desc" to "本应用为原型展示而直接引用了 API 密钥。Android APK 文件可以被轻易反编译，密钥有从 BuildConfig 等地方泄漏的风险。与他人共享 APK 时，请务必移除您的生产环境 API 密钥，或考虑使用后端代理进行安全部署。",
        "dialog_custom_bg_title" to "自定义背景图片 URL",
        "dialog_custom_bg_desc" to "请输入展示宇航或星系效果的有效 JPG/PNG 图片网址。",
        "back_btn" to "返回",
        "primary_model_label" to "默认文本模型",
        "backup_model_label" to "备用文本模型 (Fallback)",
        "embedding_model_label" to "嵌入模型",
        "unanalyzed_ribbon_title" to "有未分析的应用",
        "unanalyzed_ribbon_desc" to "自动生成 AI 分类、摘要和相关链接。",
        "running_analysis" to "AI 正在分析...",
        "cancel_btn" to "中止",
        "no_apps" to "未找到已安装的应用",
        "items_count" to "%d个应用",
        "search_placeholder" to "搜索应用或 AI 分析内容...",
        "search_icon_desc" to "搜索",
        "clear_btn_desc" to "清除",
        "ai_summary_title" to "AI 摘要",
        "related_suggestions" to "类似推荐应用",
        "re_analyze" to "重新分析",
        "close_btn" to "关闭",
        "link_error" to "无法打开链接: %s",
        "no_ai_details_title" to "此应用未被分析",
        "no_ai_details_desc" to "运行 AI 分析将自动生成类别分类、摘要、标签和相关链接。",
        "gemini_api_key_label" to "Gemini API 密钥 (自定义)",
        "gemini_api_key_placeholder" to "输入 API 密钥 (留空则使用默认密钥)",
        "correction_context_title" to "AI 修正和上下文 (可选)",
        "correction_text_placeholder" to "输入 AI 指示或修正文本...",
        "choose_file_btn" to "上传文件",
        "selected_file_label" to "已选文件: %s",
        "vector_utility" to "实用与系统",
        "vector_productivity" to "生产力与工作",
        "vector_social" to "社交与通信",
        "vector_entertainment" to "娱乐与游戏",
        "vector_creativity" to "创造与艺术",
        "vector_knowledge" to "信息与知识",
        "vector_title" to "AI 向量多维特征分析"
    )
}
